import type { Q } from "./types";

export const AML_QUESTIONS: Q[] = [
  {
    t: "SINGLE", d: "B", tier: "F", course: "aml-cft-fundamentals",
    s: "Which stage of money laundering involves first introducing criminal proceeds into the financial system?",
    o: ["Placement", "Layering", "Integration", "Structuring"], c: [0],
    oe: [null, "Layering disguises the trail after funds are already in the system.", "Integration returns funds to the criminal in apparently legitimate form.", "Structuring is a technique (often used at placement), not a stage."],
    e: "Placement is the first stage: illicit proceeds (often cash) enter the financial system, e.g., through deposits or purchases of monetary instruments.",
    p: "Cash-deposit monitoring and threshold reporting controls primarily target the placement stage.",
    tags: ["ML stages", "placement"],
  },
  {
    t: "SINGLE", d: "B", tier: "F", course: "aml-cft-fundamentals",
    s: "Which statement best describes a key difference between terrorist financing and money laundering?",
    o: [
      "Terrorist financing always involves large sums of money",
      "Terrorist financing funds may come from legitimate sources",
      "Money laundering is only concerned with drug proceeds",
      "Terrorist financing never uses the banking system",
    ], c: [1],
    e: "Terrorist financing can use legitimate income (salaries, donations, business revenue). The focus is on the destination and use of funds, not only their criminal origin.",
    p: "Because TF amounts can be small and clean, detection relies heavily on sanctions screening, intelligence-led indicators and geographic risk.",
    tags: ["terrorist financing"],
  },
  {
    t: "TRUE_FALSE", d: "B", tier: "F", course: "aml-cft-fundamentals",
    s: "Under a risk-based approach, firms must eliminate all money laundering risk before onboarding a customer.",
    o: ["True", "False"], c: [1],
    e: "False. The risk-based approach aims to identify, assess and manage risk proportionately — not to eliminate it. Firms apply controls commensurate with the assessed risk and document their rationale.",
    p: "Use documented risk appetite and EDD rather than blanket de-risking of whole customer categories.",
    tags: ["risk-based approach"],
  },
  {
    t: "SINGLE", d: "B", tier: "F", course: "aml-cft-fundamentals",
    s: "The FATF was established in 1989 by which group?",
    o: ["The United Nations General Assembly", "The G7", "The World Bank", "The Basel Committee"], c: [1],
    e: "The FATF was established by the G7 summit in Paris in 1989 to examine and develop measures to combat money laundering.",
    src: "FATF — History of the FATF", url: "https://www.fatf-gafi.org/en/the-fatf/history-of-the-fatf.html",
    tags: ["FATF"],
  },
  {
    t: "MULTIPLE", d: "I", tier: "F", course: "aml-cft-fundamentals",
    s: "Which of the following are core components of an AML/CFT compliance programme? (Select all that apply.)",
    o: ["Customer due diligence", "Suspicious activity reporting", "Guaranteeing zero financial crime losses", "Independent testing", "Training"],
    c: [0, 1, 3, 4],
    e: "CDD, reporting, independent testing and training are standard programme components. No programme can guarantee zero losses; effectiveness is judged on proportionate, well-operated controls.",
    tags: ["compliance programme"],
  },
  {
    t: "SCENARIO", d: "I", tier: "F", course: "money-laundering-stages-typologies",
    sc: "A personal account opened six weeks ago for a student receives 38 incoming transfers from different individuals, each between 150 and 900 in local currency. Within hours of each credit, the balance is transferred to an overseas crypto exchange.",
    s: "Which typology is MOST consistent with this activity?",
    o: ["Trade-based money laundering", "Money mule / pass-through account", "Structuring of cash deposits", "Loan-back scheme"], c: [1],
    e: "Many unrelated incoming credits followed by rapid onward transfer is a classic mule or pass-through pattern, often linked to fraud proceeds.",
    p: "Escalate for investigation, consider restrictions per policy, and assess whether a suspicious activity report is required without tipping off the customer.",
    tags: ["mules", "typologies"],
  },
  {
    t: "SINGLE", d: "I", course: "money-laundering-stages-typologies",
    s: "Which technique is typical of the layering stage?",
    o: ["Depositing cash below thresholds", "A chain of transfers through shell companies in several jurisdictions", "Buying a house with laundered funds", "Smuggling cash across a border"], c: [1],
    e: "Layering creates distance from the source through complex transactions, commonly using corporate vehicles and multiple jurisdictions.",
    tags: ["layering"],
  },
  {
    t: "FILL_BLANK", d: "B", tier: "F", course: "money-laundering-stages-typologies",
    s: "Breaking large amounts of cash into smaller deposits to avoid reporting thresholds is known as ______.",
    a: ["structuring", "smurfing"],
    e: "Structuring (also called smurfing when multiple people are used) is the deliberate splitting of transactions to evade reporting thresholds. In many jurisdictions structuring itself is an offence.",
    tags: ["structuring"],
  },
  {
    t: "MATCHING", d: "I", course: "money-laundering-stages-typologies",
    s: "Match each activity to the money laundering stage it most closely represents.",
    m: [
      ["Depositing cash takings from drug sales at several branches", "Placement"],
      ["Wiring funds through accounts of offshore shell companies", "Layering"],
      ["Purchasing a hotel using a 'loan' from a company the criminal controls", "Integration"],
    ],
    e: "Placement introduces funds; layering obscures their trail; integration returns them as apparently legitimate wealth.",
    tags: ["ML stages"],
  },
  {
    t: "SINGLE", d: "I", tier: "F", course: "customer-due-diligence-kyc",
    s: "Under a 25% threshold, Mr X owns 40% of Company A directly and 100% of Company B, which owns 35% of Company A. What is Mr X's total ownership of Company A?",
    o: ["40%", "35%", "75%", "100%"], c: [2],
    e: "Direct 40% + indirect 35% (100% × 35%) = 75%. Mr X is a beneficial owner.",
    p: "Always calculate indirect holdings by multiplying percentages along each chain and adding chains held by the same person.",
    tags: ["beneficial ownership"],
  },
  {
    t: "SINGLE", d: "B", tier: "F", course: "customer-due-diligence-kyc",
    s: "What is the difference between customer identification and verification?",
    o: [
      "They are the same thing",
      "Identification obtains information; verification confirms it using reliable, independent sources",
      "Verification is only required for companies",
      "Identification is optional for low-risk customers",
    ], c: [1],
    e: "Identification collects identity information; verification checks it against reliable, independent sources such as documents or trusted databases.",
    tags: ["CDD"],
  },
  {
    t: "TRUE_FALSE", d: "B", tier: "F", course: "customer-due-diligence-kyc",
    s: "A beneficial owner must always be a natural person.",
    o: ["True", "False"], c: [0],
    e: "True. Beneficial ownership looks through legal entities to the natural person(s) who ultimately own or control the customer.",
    tags: ["beneficial ownership"],
  },
  {
    t: "SHORT_ANSWER", d: "I", course: "customer-due-diligence-kyc",
    s: "Briefly explain why understanding the purpose and intended nature of a business relationship is important.",
    k: ["baseline|expected|profile", "monitor|monitoring|unusual"],
    ma: "It establishes a baseline of expected activity, which is essential for ongoing monitoring: it allows the firm to detect activity that is unusual or inconsistent with the customer's profile.",
    e: "Purpose and intended nature create the expected-activity profile that makes monitoring meaningful and supports well-evidenced suspicious activity decisions.",
    tags: ["CDD", "monitoring"],
  },
  {
    t: "SINGLE", d: "I", course: "enhanced-due-diligence-risk-assessment",
    s: "What does 'source of wealth' refer to?",
    o: [
      "The origin of the specific funds used in a transaction",
      "How the customer accumulated their total net worth",
      "The bank from which funds were transferred",
      "The customer's annual salary only",
    ], c: [1],
    oe: ["That describes source of funds.", null, "The remitting bank is not the source of wealth.", "Salary may contribute but is only part of the picture."],
    e: "Source of wealth describes how a customer's overall wealth was generated (career, business, inheritance). Source of funds relates to specific funds in the relationship or transaction.",
    tags: ["EDD", "source of wealth"],
  },
  {
    t: "MULTIPLE", d: "I", course: "enhanced-due-diligence-risk-assessment",
    s: "Which are appropriate EDD measures for a high-risk customer? (Select all that apply.)",
    o: ["Senior management approval", "Corroborating source of wealth", "More frequent reviews", "Skipping sanctions screening to save time", "Enhanced transaction monitoring"],
    c: [0, 1, 2, 4],
    e: "EDD adds scrutiny: senior approval, corroborated SoW/SoF, more frequent reviews and enhanced monitoring. Screening is never skipped.",
    tags: ["EDD"],
  },
  {
    t: "SCENARIO", d: "A", course: "enhanced-due-diligence-risk-assessment",
    sc: "A prospective private-banking client, 34, declares net worth of USD 25 million from 'consulting and digital asset trading'. They provide a one-page letter from their own accountant but no statements or tax filings. Open-source research finds no public profile of a consulting business.",
    s: "What is the MOST appropriate next step?",
    o: [
      "Approve — the accountant's letter is sufficient",
      "Request corroborating evidence of wealth generation (e.g., exchange statements, tax filings, company accounts) before any decision",
      "Decline immediately and file a report without further enquiry",
      "Approve but with a lower credit limit",
    ], c: [1],
    e: "Wealth claims should be corroborated in proportion to risk. A self-arranged letter without supporting documents is insufficient for a high-risk profile; obtain independent evidence before deciding.",
    p: "Record the plausibility gaps and the evidence requested. If explanations remain unsatisfactory, decline and consider whether suspicion exists.",
    tags: ["EDD", "source of wealth"],
  },
  {
    t: "SINGLE", d: "I", course: "transaction-monitoring-investigations",
    s: "What is the purpose of below-the-line (BTL) testing in transaction monitoring?",
    o: [
      "To close alerts faster",
      "To test whether activity just below current thresholds contains suspicious behaviour being missed",
      "To remove scenarios from production",
      "To test customer satisfaction",
    ], c: [1],
    e: "BTL testing samples activity below thresholds to determine whether thresholds are set too high and suspicious activity is being missed.",
    tags: ["tuning"],
  },
  {
    t: "INVESTIGATION", d: "I", course: "transaction-monitoring-investigations",
    sc: "An alert fires for a small import business: incoming payments rose 60% in December. Prior years show similar December spikes. Invoices for seasonal stock are on file.",
    s: "Which investigation steps are appropriate before closing the alert? (Select all that apply.)",
    o: [
      "Compare with prior years' seasonal patterns",
      "Review counterparties and geographies of the December payments",
      "Close immediately because the customer is a business",
      "Check invoices and whether goods are consistent with the business",
      "Contact the customer and tell them they triggered a monitoring alert",
    ], c: [0, 1, 3],
    oe: [null, null, "Business customers still require analysis.", null, "Disclosing monitoring or suspicion risks tipping off."],
    e: "Good practice is to compare with history, review counterparties and supporting documents, and document the rationale. Customer outreach, if needed, must avoid tipping off.",
    tags: ["alert investigation"],
  },
  {
    t: "SINGLE", d: "I", course: "suspicious-activity-reporting",
    s: "In the United States, SARs are generally due within how many calendar days after initial detection of facts that may constitute a basis for filing?",
    o: ["7", "15", "30", "90"], c: [2],
    e: "FinCEN rules generally require SAR filing no later than 30 calendar days after initial detection (with a possible extension to 60 days if no suspect is identified).",
    src: "FinCEN SAR requirements (31 CFR Chapter X)", url: "https://www.fincen.gov/",
    tags: ["SAR", "US"],
  },
  {
    t: "TRUE_FALSE", d: "B", tier: "F", course: "suspicious-activity-reporting",
    s: "Telling a customer that a suspicious activity report has been filed about them may be a criminal offence.",
    o: ["True", "False"], c: [0],
    e: "True. Tipping off is an offence in many jurisdictions. Staff must avoid disclosing reports or investigations to customers or third parties.",
    tags: ["tipping off"],
  },
  {
    t: "MULTIPLE", d: "I", course: "suspicious-activity-reporting",
    s: "Which elements make a suspicious activity report narrative useful to law enforcement? (Select all that apply.)",
    o: ["A clear summary of why the activity is suspicious", "Chronology of relevant transactions", "Unexplained internal abbreviations", "Identifiers of subjects and accounts", "Speculation beyond the evidence"],
    c: [0, 1, 3],
    e: "Useful narratives are clear, specific and evidence-based: a summary of suspicion, chronology and identifiers. Avoid jargon and speculation.",
    tags: ["SAR writing"],
  },
  {
    t: "SINGLE", d: "A", course: "correspondent-banking-aml-risk",
    s: "What is a 'nested' correspondent relationship?",
    o: [
      "A relationship with a branch in the same country",
      "When a respondent bank provides services to other banks that then access the correspondent's account indirectly",
      "A relationship secured by collateral",
      "A domestic payment scheme membership",
    ], c: [1],
    e: "Nesting occurs when a respondent's own bank customers use the correspondent account through the respondent, reducing the correspondent's visibility of the ultimate parties.",
    tags: ["correspondent banking"],
  },
  {
    t: "SINGLE", d: "I", course: "correspondent-banking-aml-risk",
    s: "Which FATF Recommendation addresses wire transfers and the travel of originator and beneficiary information?",
    o: ["Recommendation 10", "Recommendation 13", "Recommendation 16", "Recommendation 20"], c: [2],
    e: "Recommendation 16 covers wire transfers (payment transparency). R.10 is CDD, R.13 correspondent banking, R.20 suspicious transaction reporting.",
    src: "FATF Recommendations", url: "https://www.fatf-gafi.org/en/publications/Fatfrecommendations/Fatf-recommendations.html",
    tags: ["FATF", "payment transparency"],
  },
  {
    t: "SINGLE", d: "A", course: "aml-governance-compliance-programs",
    s: "In the three lines model, which function typically provides independent assurance over the AML programme?",
    o: ["First line business teams", "Second line compliance", "Third line internal audit", "External customers"], c: [2],
    e: "Internal audit (third line) provides independent assurance. The second line sets policy, advises and challenges; the first line owns and operates controls.",
    tags: ["governance"],
  },
];

export const SANCTIONS_QUESTIONS: Q[] = [
  {
    t: "SINGLE", d: "B", tier: "F", course: "global-sanctions-fundamentals",
    s: "Which US government office administers most US economic and trade sanctions programmes?",
    o: ["FinCEN", "OFAC", "The SEC", "The Federal Reserve"], c: [1],
    e: "The Office of Foreign Assets Control (OFAC), part of the US Department of the Treasury, administers and enforces most US economic sanctions programmes.",
    src: "U.S. Department of the Treasury — OFAC", url: "https://ofac.treasury.gov/",
    tags: ["OFAC"],
  },
  {
    t: "SINGLE", d: "B", tier: "F", course: "global-sanctions-fundamentals",
    s: "In the United Kingdom, which body implements and enforces financial sanctions?",
    o: ["The Financial Conduct Authority", "The Office of Financial Sanctions Implementation (OFSI)", "The Bank of England", "The Serious Fraud Office"], c: [1],
    e: "OFSI, part of HM Treasury, implements and enforces UK financial sanctions. Designations are generally made by the FCDO under SAMLA 2018.",
    url: "https://www.gov.uk/government/organisations/office-of-financial-sanctions-implementation",
    tags: ["UK", "OFSI"],
  },
  {
    t: "MULTIPLE", d: "I", tier: "F", course: "global-sanctions-fundamentals",
    s: "Which of the following are components of OFAC's Framework for OFAC Compliance Commitments? (Select all that apply.)",
    o: ["Management commitment", "Risk assessment", "Internal controls", "Testing and auditing", "Training", "Guaranteed approval of licences"],
    c: [0, 1, 2, 3, 4],
    e: "The 2019 framework identifies five essential components: management commitment, risk assessment, internal controls, testing and auditing, and training.",
    src: "OFAC — A Framework for OFAC Compliance Commitments (2019)", url: "https://ofac.treasury.gov/",
    tags: ["compliance programme", "OFAC"],
  },
  {
    t: "TRUE_FALSE", d: "B", tier: "F", course: "global-sanctions-fundamentals",
    s: "UN Security Council sanctions are binding on all UN member states, which implement them through domestic measures.",
    o: ["True", "False"], c: [0],
    e: "True. Measures adopted under Chapter VII of the UN Charter bind member states, who give them effect in domestic law.",
    tags: ["UN"],
  },
  {
    t: "SINGLE", d: "I", course: "ofac-50-percent-rule-ownership",
    s: "Under OFAC's 50 Percent Rule, SDN A owns 30% and SDN B owns 25% of Company X. What is Company X's status?",
    o: ["Not blocked — no single SDN owns 50%", "Blocked — aggregate ownership by blocked persons is 55%", "Blocked only if listed on the SDN List", "Subject only to sectoral restrictions"], c: [1],
    e: "OFAC aggregates ownership held by multiple blocked persons. 30% + 25% = 55% ≥ 50%, so Company X is blocked by operation of law.",
    src: "OFAC Revised Guidance on Entities Owned by Persons Whose Property Is Blocked (Aug. 13, 2014)", url: "https://ofac.treasury.gov/",
    tags: ["50 percent rule", "aggregation"],
  },
  {
    t: "SINGLE", d: "I", course: "ofac-50-percent-rule-ownership",
    s: "Which statement about control under OFAC's 50 Percent Rule is correct?",
    o: [
      "An entity controlled by an SDN is automatically blocked regardless of ownership",
      "The rule is based on ownership; control alone does not trigger blocking under the rule, though caution is advised",
      "Control is irrelevant to sanctions risk",
      "Control counts as 25% ownership",
    ], c: [1],
    e: "OFAC's rule is ownership-based. Entities controlled but not 50%+ owned by blocked persons are not automatically blocked, but OFAC advises caution as they may be designated and dealings may involve blocked persons.",
    tags: ["50 percent rule", "control"],
  },
  {
    t: "SCENARIO", d: "A", course: "ofac-50-percent-rule-ownership",
    sc: "SDN C owns 60% of Alpha Ltd. Alpha Ltd owns 20% of Gamma Ltd. SDN D owns 35% of Gamma Ltd. No other blocked persons are involved.",
    s: "Is Gamma Ltd blocked under OFAC's 50 Percent Rule?",
    o: [
      "No — SDN D owns only 35%",
      "Yes — Alpha is blocked (60%), so its 20% counts; 20% + 35% = 55%",
      "No — indirect holdings are never counted",
      "Yes — because SDN C controls Gamma",
    ], c: [1],
    e: "Alpha is blocked because SDN C owns 60% of it. Alpha's 20% interest in Gamma is therefore blocked ownership. Adding SDN D's 35% gives 55% — Gamma is blocked.",
    p: "Document each layer, percentage and source, and show the aggregation arithmetic in the case file.",
    tags: ["50 percent rule", "indirect ownership"],
  },
  {
    t: "SINGLE", d: "A", course: "ofac-50-percent-rule-ownership",
    sc: "SDN A owns 40% of Company P, which is not otherwise blocked. Company P owns 100% of Company Q.",
    s: "Under OFAC's 50 Percent Rule alone, is Company Q blocked?",
    o: ["Yes, SDN A indirectly owns 40% of Q", "No, because P is not blocked, its holding in Q is not counted as blocked ownership", "Yes, 100% ownership always triggers blocking", "Only if Q is in a sanctioned country"], c: [1],
    e: "Ownership is traced through blocked entities. P is only 40% owned by an SDN, so it is not blocked; its interest in Q does not count toward blocked ownership. Heightened risk remains, and enhanced diligence is prudent.",
    tags: ["50 percent rule"],
  },
  {
    t: "SINGLE", d: "I", course: "un-eu-uk-sanctions-regimes",
    s: "How does the OFAC ownership threshold differ from the EU and UK ownership tests?",
    o: [
      "OFAC uses 'more than 50%'; EU/UK use '50% or more'",
      "OFAC uses '50% or more' (aggregate); EU/UK use 'more than 50%', plus control tests",
      "All three use 25%",
      "There is no ownership test in the EU",
    ], c: [1],
    e: "OFAC blocks entities owned 50% or more in aggregate by blocked persons. The EU and UK apply 'more than 50%' ownership tests together with control criteria.",
    tags: ["ownership", "EU", "UK"],
  },
  {
    t: "SINGLE", d: "I", course: "ofac-sanctions-sdn-non-sdn",
    s: "A payment involves a party on OFAC's Sectoral Sanctions Identifications (SSI) List but not on the SDN List. What is generally correct?",
    o: [
      "The funds must always be blocked",
      "Only the activities prohibited by the applicable directive are restricted; other dealings may be permissible",
      "SSI parties are exempt from all US sanctions",
      "The payment must be rejected in all cases",
    ], c: [1],
    e: "SSI listing imposes activity-specific restrictions defined in directives (e.g., new debt beyond certain maturities). It does not by itself require blocking.",
    tags: ["SSI", "non-SDN"],
  },
  {
    t: "MATCHING", d: "I", course: "ofac-sanctions-sdn-non-sdn",
    s: "Match each OFAC term with its meaning.",
    m: [
      ["Blocking", "Freezing property in which a blocked person has an interest"],
      ["Rejecting", "Declining a prohibited transaction with no blockable interest"],
      ["General licence", "Authorisation available to all persons meeting its conditions"],
      ["Specific licence", "Authorisation issued to a particular applicant"],
    ],
    e: "Blocking freezes property; rejecting refuses a prohibited transaction; general licences authorise classes of transactions; specific licences are issued case-by-case.",
    tags: ["OFAC", "licensing"],
  },
  {
    t: "FILL_BLANK", d: "I", course: "ofac-sanctions-sdn-non-sdn",
    s: "Reports of blocked property and rejected transactions must be filed with OFAC within ______ business days.",
    a: ["10", "ten"],
    e: "OFAC's Reporting, Procedures and Penalties Regulations require reports of blocked property and rejected transactions within 10 business days.",
    src: "31 CFR Part 501", url: "https://ofac.treasury.gov/",
    tags: ["OFAC", "reporting"],
  },
  {
    t: "SCENARIO", d: "B", tier: "F", course: "sanctions-screening-alert-investigation",
    sc: "Customer: Ali Hassan, DOB 12 March 1990, British national, London address. Screening alert: listed individual 'Ali HASAN', DOB 1962, place of birth Damascus.",
    s: "What is the most appropriate disposition?",
    o: [
      "True match — block the account",
      "False positive — close, documenting the differing DOB and nationality",
      "Escalate because the names are similar",
      "Ask the customer whether they are sanctioned",
    ], c: [1],
    e: "Secondary identifiers (DOB 1990 vs 1962; British vs listed profile) clearly differ. Record the identifiers compared and close as a false positive.",
    p: "Strong dispositions name the identifiers compared and their values, not simply 'different person'.",
    tags: ["screening", "false positive"],
  },
  {
    t: "SINGLE", d: "B", tier: "F", course: "sanctions-screening-alert-investigation",
    s: "What is the primary unique identifier for a vessel in sanctions screening?",
    o: ["Vessel name", "Flag state", "IMO number", "Port of registry"], c: [2],
    e: "The IMO number stays with the ship for life despite name, flag or ownership changes, making it the primary vessel identifier.",
    tags: ["maritime", "screening"],
  },
  {
    t: "MULTIPLE", d: "I", course: "sanctions-false-positives-escalations",
    s: "Which are SAFE ways to reduce sanctions screening false positives? (Select all that apply.)",
    o: [
      "Improving customer data quality (e.g., capturing DOB and country)",
      "Tested use of secondary identifiers in matching rules",
      "Removing aliases from the list to reduce noise",
      "Governed good-guy lists that are re-screened when lists change",
      "Asking customers to change payment references to avoid hits",
    ], c: [0, 1, 3],
    oe: [null, null, "Removing aliases creates screening gaps.", null, "Encouraging reference changes to avoid screening may be evasion."],
    e: "Data quality, tested secondary-identifier logic and governed good-guy lists reduce noise safely. Removing list content or coaching customers creates serious risk.",
    tags: ["false positives"],
  },
  {
    t: "MULTIPLE", d: "I", course: "sanctions-evasion-typologies",
    s: "Which are common sanctions evasion indicators? (Select all that apply.)",
    o: [
      "Newly incorporated counterparty in a transshipment hub placing large orders",
      "Payment from an unrelated third party in another jurisdiction",
      "Long-standing domestic customer paying a known supplier",
      "Reluctance to provide end-use information",
      "Share transfer to a relative shortly after a designation",
    ], c: [0, 1, 3, 4],
    e: "New entities in transshipment hubs, third-party payments, end-use reluctance and post-designation transfers to relatives are recognised evasion indicators.",
    tags: ["evasion"],
  },
  {
    t: "MULTIPLE", d: "A", course: "maritime-shipping-trade-sanctions",
    s: "Which are deceptive shipping practices highlighted in government maritime advisories? (Select all that apply.)",
    o: ["Disabling or manipulating AIS", "Ship-to-ship transfers to disguise cargo origin", "Using the IMO number consistently", "Frequent flag changes (flag hopping)", "Falsifying cargo documents"],
    c: [0, 1, 3, 4],
    e: "AIS manipulation, illicit STS transfers, flag hopping and document falsification are commonly cited deceptive practices. Consistent IMO use is normal.",
    tags: ["maritime", "evasion"],
  },
  {
    t: "SHORT_ANSWER", d: "A", course: "ownership-control-beneficial-ownership",
    s: "Two weeks after designation, a businessman transfers his 70% stake to his adult son for nominal consideration, but remains listed as chairman on the company website. Briefly state your concern.",
    k: ["control|controlled", "evasion|evade|circumvent|proxy|nominee"],
    ma: "The transfer may be a sham designed to evade sanctions: the designated person appears to retain control (still chairman), and the son may be acting as a proxy or nominee. Ownership and control should be treated as potentially remaining with the designated person pending evidence.",
    e: "Timing, nominal consideration, a family transferee and continued public role are strong indicators that the designated person retains control and the transfer may be an evasion attempt.",
    tags: ["control", "evasion"],
  },
  {
    t: "SINGLE", d: "A", course: "sanctions-exposure-nexus-analysis",
    s: "A non-US company pays for goods in US dollars cleared through a US bank. Why can this create US sanctions exposure?",
    o: [
      "It cannot — non-US companies are never subject to US sanctions",
      "Dollar clearing involves US financial institutions; causing them to process prohibited transactions can create liability",
      "Only euro payments create exposure",
      "Because all dollar payments require an OFAC licence",
    ], c: [1],
    e: "USD clearing generally involves US persons (banks). Causing them to process transactions involving sanctioned parties can violate US sanctions — a key nexus point.",
    tags: ["nexus", "USD"],
  },
  {
    t: "TRUE_FALSE", d: "I", course: "sectoral-sanctions-restrictions",
    s: "Extended payment terms granted to a sectorally sanctioned entity can, in some cases, constitute prohibited 'new debt'.",
    o: ["True", "False"], c: [0],
    e: "True. Under certain directives, extended payment terms beyond permitted maturities can be treated as debt. Front-office staff should escalate unusual terms.",
    tags: ["sectoral sanctions"],
  },
  {
    t: "SINGLE", d: "I", course: "sanctions-risk-assessment-approval",
    s: "Residual sanctions risk is best described as:",
    o: ["Inherent risk before controls", "Risk remaining after effective controls are applied", "The number of screening alerts", "Risk transferred to a correspondent bank"], c: [1],
    e: "Residual risk is what remains after considering the design and operating effectiveness of controls. It is compared to risk appetite to determine actions.",
    tags: ["risk assessment"],
  },
  {
    t: "SINGLE", d: "I", course: "sanctions-due-diligence-counterparties",
    s: "Why is name screening alone insufficient for sanctions compliance?",
    o: [
      "Screening is illegal in some countries",
      "Unlisted entities may be owned or controlled by designated persons, and goods or geographies can create exposure",
      "Lists are always outdated",
      "Screening only covers individuals",
    ], c: [1],
    e: "Ownership rules, control, geographic and trade restrictions mean parties not named on lists can still be restricted. Due diligence complements screening.",
    tags: ["due diligence"],
  },
];
