import type { Q } from "./types";

/** Second batch of original questions, spread across all topics. */
export const BATCH2_QUESTIONS: Q[] = [
  // AML / KYC
  { t: "SINGLE", d: "B", tier: "F", course: "aml-cft-fundamentals", s: "What is a 'predicate offence'?", o: ["An offence committed by a bank", "The underlying crime that generates the proceeds being laundered", "A minor regulatory breach", "An offence involving only cash"], c: [1], e: "Predicate offences (e.g., fraud, corruption, drug trafficking, tax crimes) generate the criminal proceeds that are laundered.", tags: ["predicate offences"] },
  { t: "SINGLE", d: "B", tier: "F", course: "aml-cft-fundamentals", s: "Which body typically receives and analyses suspicious transaction reports in a country?", o: ["The central bank's monetary policy committee", "The Financial Intelligence Unit (FIU)", "The stock exchange", "The tax court"], c: [1], e: "FIUs receive, analyse and disseminate suspicious transaction reports and related intelligence to competent authorities.", tags: ["FIU"] },
  { t: "TRUE_FALSE", d: "B", tier: "F", course: "aml-cft-fundamentals", s: "Designated non-financial businesses and professions (DNFBPs), such as lawyers and real estate agents, can have AML obligations under FATF standards.", o: ["True", "False"], c: [0], e: "True. FATF standards extend key preventive measures to DNFBPs including casinos, real estate agents, dealers in precious metals and stones, lawyers, notaries, accountants and TCSPs in specified circumstances.", tags: ["DNFBPs"] },
  { t: "SINGLE", d: "I", course: "money-laundering-stages-typologies", s: "Which feature makes real estate attractive for laundering?", o: ["It is always paid in small amounts", "Large values can be moved in a single transaction and assets may hold or grow in value", "Property purchases are never recorded", "It cannot be bought through companies"], c: [1], e: "High-value single transactions and value retention, especially via opaque companies or all-cash deals, make property attractive.", tags: ["real estate"] },
  { t: "SINGLE", d: "I", course: "money-laundering-stages-typologies", s: "A 'front company' differs from a 'shell company' because a front company:", o: ["Has no operations at all", "Conducts some genuine business to disguise illicit flows", "Is always listed on a stock exchange", "Is only used for tax planning"], c: [1], e: "Front companies mix genuine activity with illicit funds, while shell companies have little or no real operations.", tags: ["corporate vehicles"] },
  { t: "SCENARIO", d: "I", course: "customer-due-diligence-kyc", sc: "A company applying for an account lists its owners as three companies in different jurisdictions, each owned by nominee shareholders. The applicant says it 'cannot disclose' the ultimate owners for confidentiality reasons.", s: "What should the firm do?", o: ["Open the account — confidentiality is legitimate", "Not proceed unless beneficial ownership can be identified and verified; consider whether the refusal is suspicious", "Open the account with a lower limit", "Accept a declaration signed by a nominee director"], c: [1], e: "If CDD, including beneficial ownership, cannot be completed, the firm should not establish the relationship and should consider whether a report is required.", tags: ["beneficial ownership"] },
  { t: "SINGLE", d: "I", course: "customer-due-diligence-kyc", s: "If no natural person meets the ownership threshold for a company, many regimes require the firm to identify:", o: ["No one", "The senior managing official", "The company's auditor", "The largest corporate shareholder"], c: [1], e: "Where no beneficial owner is identified through ownership or control, the senior managing official is typically recorded, with the rationale documented.", tags: ["beneficial ownership"] },
  { t: "MULTIPLE", d: "I", course: "enhanced-due-diligence-risk-assessment", s: "Which are indicators that a customer's source of wealth explanation may be implausible? (Select all that apply.)", o: ["Wealth far exceeds typical earnings for the stated career", "Unexplained gaps in the wealth timeline", "Independent documents corroborate each step", "Links to state contracts in a high-corruption sector", "No public footprint for a claimed large business"], c: [0, 1, 3, 4], e: "Mismatches with career norms, timeline gaps, corruption-sensitive links and absent public footprint all warrant further corroboration.", tags: ["source of wealth"] },
  { t: "SINGLE", d: "A", course: "correspondent-banking-aml-risk", s: "Which industry questionnaire is widely used for correspondent banking due diligence?", o: ["The Wolfsberg CBDDQ", "The Basel III LCR template", "The ISO 20022 message catalogue", "The SWIFT gpi tracker"], c: [0], e: "The Wolfsberg Group's Correspondent Banking Due Diligence Questionnaire (CBDDQ) is widely used to standardise respondent information.", url: "https://wolfsberg-group.org/", tags: ["correspondent banking"] },
  { t: "SINGLE", d: "A", course: "aml-governance-compliance-programs", s: "A remediation issue should be closed when:", o: ["The fix has been implemented", "Evidence shows the fixed control operates effectively", "The deadline passes", "The regulator stops asking"], c: [1], e: "Good practice is to validate effectiveness before closure, not merely implementation.", tags: ["remediation"] },
  { t: "SINGLE", d: "I", course: "cryptocurrency-virtual-asset-aml", s: "Why should blockchain analytics attributions be treated with care?", o: ["They are always wrong", "They are probabilistic intelligence that should be corroborated and documented with confidence levels", "They are legally binding", "They reveal customers' names directly"], c: [1], e: "Attributions rely on clustering heuristics and intelligence; corroborate and record the tool, date and methodology.", tags: ["blockchain analytics"] },
  { t: "SINGLE", d: "I", course: "cryptocurrency-virtual-asset-aml", s: "A wallet controlled directly by its user, rather than by a service provider, is called:", o: ["A custodial wallet", "A self-hosted (unhosted) wallet", "A nested VASP", "A mixer"], c: [1], e: "Self-hosted wallets are controlled by the user holding the private keys, without an intermediary.", tags: ["wallets"] },

  // Sanctions
  { t: "SINGLE", d: "B", tier: "F", course: "global-sanctions-fundamentals", s: "An asset freeze typically prohibits:", o: ["Only travel by the designated person", "Dealing with the designated person's funds and making funds available to them", "Publishing news about the person", "Only exports of weapons"], c: [1], e: "Asset freezes prohibit dealing with frozen funds and economic resources, and making funds or economic resources available, directly or indirectly, to designated persons.", tags: ["asset freeze"] },
  { t: "SINGLE", d: "B", tier: "F", course: "global-sanctions-fundamentals", s: "Which legislation provides the main framework for UK sanctions?", o: ["The Bribery Act 2010", "The Sanctions and Anti-Money Laundering Act 2018", "The Fraud Act 2006", "The Companies Act 2006"], c: [1], e: "SAMLA 2018 enables the UK to make sanctions regulations.", url: "https://www.legislation.gov.uk/ukpga/2018/13/contents", tags: ["UK"] },
  { t: "TRUE_FALSE", d: "I", course: "global-sanctions-fundamentals", s: "OFAC civil penalties can be imposed on a strict liability basis, meaning a violation can occur without intent.", o: ["True", "False"], c: [0], e: "True. OFAC civil liability is strict; intent affects penalty determination under the Enforcement Guidelines but is not required for a violation.", tags: ["enforcement", "OFAC"] },
  { t: "SINGLE", d: "I", course: "un-eu-uk-sanctions-regimes", s: "What is the EU Blocking Statute designed to do?", o: ["Block all payments to the EU", "Protect EU operators against the effects of specified extraterritorial third-country sanctions", "Freeze assets of EU citizens", "Require EU banks to comply with US sanctions"], c: [1], e: "The Blocking Statute (Council Regulation (EC) No 2271/96) prohibits compliance with specified extraterritorial measures and allows recovery of damages.", tags: ["EU", "blocking statute"] },
  { t: "SINGLE", d: "I", course: "un-eu-uk-sanctions-regimes", s: "EU economic restrictive measures are implemented through Council Regulations adopted under which Treaty article?", o: ["Article 215 TFEU", "Article 50 TEU", "Article 101 TFEU", "Article 5 TEU"], c: [0], e: "Article 215 TFEU provides the legal basis for Council Regulations implementing economic and financial restrictive measures following a CFSP Decision.", tags: ["EU"] },
  { t: "SINGLE", d: "I", course: "ofac-sanctions-sdn-non-sdn", s: "Which persons are 'US persons' for OFAC purposes?", o: ["Only US citizens living in the US", "US citizens and permanent residents wherever located, US-organised entities and their foreign branches, and anyone in the US", "Any company using US software", "Only US government employees"], c: [1], e: "US persons include US citizens and permanent resident aliens wherever located, entities organised under US law (including foreign branches), and any person in the United States.", tags: ["US persons"] },
  { t: "SINGLE", d: "A", course: "ofac-sanctions-sdn-non-sdn", s: "Which of the following best describes 'secondary sanctions'?", o: ["Sanctions on US persons only", "Measures that target non-US persons for engaging in specified activities, even without a US nexus", "Sanctions imposed by the UN", "A second designation of the same person"], c: [1], e: "Secondary sanctions threaten consequences for non-US persons who engage in certain activities with sanctioned targets.", tags: ["secondary sanctions"] },
  { t: "SINGLE", d: "I", course: "ofac-50-percent-rule-ownership", s: "SDN A owns 50% of Company Y. Company Y owns 50% of Company Z. Under OFAC's rule, which entities are blocked?", o: ["Neither", "Only Y", "Both Y and Z", "Only Z"], c: [2], e: "Y is 50% owned by an SDN, so it is blocked. Y's 50% holding in Z is blocked ownership, so Z is also blocked.", tags: ["50 percent rule"] },
  { t: "SINGLE", d: "I", course: "sanctions-screening-alert-investigation", s: "Lowering a fuzzy-matching threshold generally results in:", o: ["Fewer alerts and fewer missed matches", "More alerts (more false positives) and fewer missed variants", "No change", "Automatic blocking"], c: [1], e: "Lower thresholds catch more name variants but increase alert volumes and false positives.", tags: ["fuzzy matching"] },
  { t: "MULTIPLE", d: "I", course: "sanctions-screening-alert-investigation", s: "Which secondary identifiers help resolve an individual name-screening alert? (Select all that apply.)", o: ["Date of birth", "Nationality", "Favourite colour", "Place of birth", "Passport or national ID number"], c: [0, 1, 3, 4], e: "DOB, nationality, place of birth and identification numbers are standard secondary identifiers.", tags: ["screening"] },
  { t: "SCENARIO", d: "I", course: "sanctions-screening-alert-investigation", sc: "A payment's remittance information reads: 'Freight charges for MV Ocean Pearl'. Screening hits on a vessel named 'Ocean Pearl' on a sanctions list.", s: "What should you check first?", o: ["The payer's favourite port", "The vessel's IMO number against the listed vessel's IMO number", "Whether 'Ocean Pearl' is a common name", "The payment amount only"], c: [1], e: "Vessel names change and repeat; the IMO number is the decisive identifier.", tags: ["vessels"] },
  { t: "SINGLE", d: "A", course: "sanctions-evasion-typologies", s: "Transshipment in the context of sanctions evasion refers to:", o: ["Shipping goods in two containers", "Routing goods through an intermediary jurisdiction to disguise the true destination or origin", "Insuring cargo twice", "Selling goods at sea"], c: [1], e: "Transshipment through third countries is a common method of concealing destination or origin.", tags: ["transshipment"] },
  { t: "SINGLE", d: "A", course: "sanctions-exposure-nexus-analysis", s: "Under OFAC rules, a US person approving a transaction by a foreign subsidiary that would be prohibited for a US person may be:", o: ["Exempt", "Facilitating a prohibited transaction", "Required to file a SAR only", "Acting under a general licence automatically"], c: [1], e: "US persons are prohibited from facilitating transactions by foreign persons that would be prohibited if performed by a US person.", tags: ["facilitation"] },

  // Fraud
  { t: "SINGLE", d: "B", tier: "F", course: "fraud-fundamentals-typologies", s: "Account takeover is a form of:", o: ["First-party fraud", "Third-party fraud", "Insider fraud", "Tax evasion"], c: [1], e: "In account takeover, a criminal gains control of a genuine customer's account — third-party fraud.", tags: ["account takeover"] },
  { t: "SINGLE", d: "I", course: "payment-fraud-app-scams", s: "What makes authorised push payment (APP) fraud difficult to prevent?", o: ["It only involves cash", "The genuine customer authorises the payment after being manipulated", "It never uses online banking", "Banks cannot see payment amounts"], c: [1], e: "The payment passes authentication because the real customer makes it; detection relies on behavioural signals and effective interventions.", tags: ["APP fraud"] },
  { t: "SCENARIO", d: "I", course: "payment-fraud-app-scams", sc: "A business receives an email from a long-standing supplier stating its bank details have changed, with an invoice due today. The email domain differs by one letter from the supplier's usual domain.", s: "What is the best control?", o: ["Pay to the new account to avoid late fees", "Verify the change by calling the supplier on a known, independently sourced number before paying", "Reply to the email to confirm", "Pay half to each account"], c: [1], e: "Invoice/mandate fraud relies on spoofed communications. Independent call-back verification is the key control.", tags: ["invoice fraud", "BEC"] },
  { t: "SINGLE", d: "I", course: "account-takeover-identity-fraud", s: "A SIM swap attack primarily allows a criminal to:", o: ["Clone a payment card", "Intercept one-time passcodes and calls sent to the victim's phone number", "Physically steal the victim's phone", "Change the victim's credit score"], c: [1], e: "By porting the victim's number, criminals receive SMS OTPs and calls, enabling account takeover.", tags: ["SIM swap"] },
  { t: "SINGLE", d: "I", course: "card-digital-payment-fraud", s: "'Friendly fraud' refers to:", o: ["Fraud between friends", "A genuine cardholder disputing a legitimate transaction to obtain a refund", "Merchant discounting", "Scams on social media"], c: [1], e: "Friendly fraud is first-party misuse of chargeback rights.", tags: ["chargebacks"] },
  { t: "MULTIPLE", d: "I", course: "mule-accounts-fraud-networks", s: "Which behaviours suggest a mule account? (Select all that apply.)", o: ["Dormant account suddenly receiving many incoming payments", "Rapid outbound transfers soon after credits", "Salary credited monthly and bills paid", "Device shared with other unrelated accounts", "Cash withdrawals immediately after credits"], c: [0, 1, 3, 4], e: "Sudden inflows, rapid outflows, shared devices and immediate cash-outs are common mule indicators.", tags: ["mules"] },
  { t: "SINGLE", d: "A", course: "fraud-investigations-evidence", s: "In an investigation report, findings should:", o: ["Mix facts with opinions freely", "Separate facts (with evidence references) from analysis and conclusions", "Avoid referencing evidence", "Focus on the investigator's feelings"], c: [1], e: "Clear separation of evidenced facts and analysis makes reports credible and usable.", tags: ["reporting"] },

  // ABC
  { t: "SINGLE", d: "I", course: "bribery-corruption-risk-assessment", s: "Which sector is commonly regarded as higher risk for bribery?", o: ["Public procurement-heavy infrastructure and construction", "Retail bakery", "Personal fitness coaching", "Stationery supply to households"], c: [0], e: "Sectors with large public contracts, licensing and many intermediaries — such as infrastructure, extractives and defence — carry higher bribery risk.", tags: ["sector risk"] },
  { t: "SINGLE", d: "I", course: "abc-fundamentals", s: "Which international convention requires parties to criminalise bribery of foreign public officials in international business transactions?", o: ["The OECD Anti-Bribery Convention", "The Paris Agreement", "The Geneva Conventions", "The Basel Accords"], c: [0], e: "The OECD Convention on Combating Bribery of Foreign Public Officials in International Business Transactions requires parties to criminalise foreign bribery.", url: "https://www.oecd.org/en/topics/anti-bribery.html", tags: ["OECD"] },
  { t: "SINGLE", d: "A", course: "corporate-liability-internal-investigations", s: "A deferred prosecution agreement (DPA) generally:", o: ["Ends all liability without conditions", "Suspends prosecution subject to the company meeting agreed conditions, such as penalties and compliance improvements", "Is a type of civil lawsuit", "Is only available to individuals"], c: [1], e: "DPAs defer prosecution while the company complies with conditions such as financial penalties, co-operation and compliance reforms.", tags: ["DPA"] },
  { t: "SINGLE", d: "I", course: "pep-risk-corruption-exposure", s: "Close associates of a PEP are relevant because:", o: ["They are always public officials", "They may be used to hold or move the proceeds of corruption on the PEP's behalf", "They are exempt from due diligence", "They must be refused service"], c: [1], e: "Corrupt officials often use family members and close associates to disguise ownership of illicit wealth.", tags: ["PEP"] },

  // Trade / Export / Governance / Investigations
  { t: "SINGLE", d: "I", course: "trade-based-money-laundering", s: "Goods shipped in a quantity different from the invoiced quantity is known as:", o: ["Over/under-shipment", "Phantom shipment", "Multiple invoicing", "Transshipment"], c: [0], e: "Over- or under-shipment misrepresents quantities to move value.", tags: ["TBML"] },
  { t: "SINGLE", d: "I", course: "trade-based-money-laundering", s: "A 'phantom shipment' means:", o: ["Goods shipped at night", "No goods are actually shipped; documents are fabricated", "Goods shipped by air", "Goods lost at sea"], c: [1], e: "Phantom shipments involve payments supported by fictitious documents for goods that never move.", tags: ["TBML"] },
  { t: "SINGLE", d: "I", course: "trade-finance-financial-crime", s: "Under a letter of credit, the issuing bank pays against:", o: ["The buyer's verbal confirmation", "Presentation of documents that comply with the credit's terms", "Physical inspection of goods by the bank", "Any invoice"], c: [1], e: "LCs are documentary: banks deal in documents, not goods, and pay against complying presentations.", tags: ["letters of credit"] },
  { t: "MULTIPLE", d: "I", course: "export-controls-dual-use-goods", s: "Which are export-control diversion red flags? (Select all that apply.)", o: ["Customer declines to state the end use", "Freight forwarder listed as final destination", "Item performance far exceeds stated need", "Customer requests installation and training at the known end-user site", "Payment by an unrelated third party"], c: [0, 1, 2, 4], e: "Reluctance about end use, forwarders as consignees, over-specification and third-party payments are diversion indicators. On-site installation at a known end user is typically reassuring.", tags: ["diversion"] },
  { t: "SINGLE", d: "I", course: "export-controls-dual-use-goods", s: "The EU dual-use export control regime is set out primarily in:", o: ["Regulation (EU) 2021/821", "Regulation (EU) 2016/679", "Directive 2015/849", "Regulation (EU) 2023/1114"], c: [0], e: "Regulation (EU) 2021/821 governs the EU regime for controlling exports, brokering, technical assistance, transit and transfer of dual-use items.", url: "https://eur-lex.europa.eu/eli/reg/2021/821/oj", tags: ["EU", "dual-use"] },
  { t: "SINGLE", d: "A", course: "financial-crime-audit-control-testing", s: "An audit finding should typically describe:", o: ["Only the auditor's opinion", "Condition, criteria, cause, consequence and corrective action", "The auditor's recommendations for staff promotions", "Only the sample size"], c: [1], e: "The 5C structure provides a complete, actionable finding.", tags: ["audit"] },
  { t: "SINGLE", d: "A", course: "financial-crime-risk-governance", s: "Individual accountability regimes, such as the UK SM&CR, aim to:", o: ["Remove responsibility from senior managers", "Assign clear responsibilities to named senior individuals", "Replace compliance functions", "Eliminate board oversight"], c: [1], e: "Accountability regimes allocate prescribed responsibilities to named senior managers, improving ownership of risk.", tags: ["accountability"] },
  { t: "SINGLE", d: "I", course: "fraud-investigations-evidence", s: "When imaging a laptop for an investigation, calculating a hash value helps to:", o: ["Speed up the laptop", "Demonstrate the copy is identical to the original and has not been altered", "Encrypt emails", "Delete duplicate files"], c: [1], e: "Hash values verify integrity; matching hashes show the forensic image is an exact copy.", tags: ["digital evidence"] },
  { t: "INVESTIGATION", d: "A", course: "transaction-monitoring-investigations", sc: "A corporate customer described as a small furniture retailer begins receiving large incoming payments from unrelated companies in several countries, immediately forwarding them to a trading company abroad. Payment references read 'services'.", s: "Which analyses would help determine whether the activity is suspicious? (Select all that apply.)", o: ["Compare activity with the customer's declared business and turnover", "Research the counterparties' business and ownership", "Summarise inflows versus outflows and timing", "Close the alert because the customer is a registered company", "Check for links between the counterparties (shared addresses, directors)"], c: [0, 1, 2, 4], e: "Profile comparison, counterparty research, flow analysis and link analysis are core techniques. Registration alone provides no assurance.", tags: ["investigation"] },
  { t: "SINGLE", d: "I", course: "crypto-assets-vasps", s: "The EU regulation establishing a framework for crypto-asset issuers and service providers is known as:", o: ["MiFID II", "MiCA", "PSD2", "GDPR"], c: [1], e: "The Markets in Crypto-Assets Regulation (MiCA), Regulation (EU) 2023/1114, regulates crypto-asset issuance and crypto-asset service providers.", url: "https://eur-lex.europa.eu/eli/reg/2023/1114/oj", tags: ["MiCA"] },
  { t: "FILL_BLANK", d: "I", course: "export-controls-dual-use-goods", s: "The multilateral export control regime covering conventional arms and dual-use goods and technologies is the ______ Arrangement.", a: ["Wassenaar"], e: "The Wassenaar Arrangement promotes transparency and responsibility in transfers of conventional arms and dual-use goods and technologies.", url: "https://www.wassenaar.org/", tags: ["Wassenaar"] },
];
