import type { Q } from "./types";

export const FRAUD_QUESTIONS: Q[] = [
  {
    t: "SINGLE", d: "B", tier: "F", course: "fraud-fundamentals-typologies",
    s: "What are the three elements of Cressey's fraud triangle?",
    o: ["Pressure, opportunity, rationalisation", "Motive, means, method", "Prevent, detect, respond", "Greed, fear, urgency"], c: [0],
    e: "The fraud triangle comprises pressure (motivation), opportunity (weak controls) and rationalisation (self-justification).",
    tags: ["fraud triangle"],
  },
  {
    t: "SINGLE", d: "B", tier: "F", course: "fraud-fundamentals-typologies",
    s: "A customer inflates their income on a loan application. This is an example of:",
    o: ["Third-party fraud", "First-party fraud", "Account takeover", "APP fraud"], c: [1],
    e: "First-party fraud is committed by the customer themselves, e.g., misrepresenting information to obtain credit.",
    tags: ["first-party fraud"],
  },
  {
    t: "SCENARIO", d: "I", tier: "F", course: "payment-fraud-app-scams",
    sc: "A customer calls, distressed, saying 'the bank's fraud team' phoned and told them their account is compromised and they must move savings to a new 'safe account' immediately. They are asking you to process the transfer quickly.",
    s: "What is the most likely scenario and best response?",
    o: [
      "A genuine bank process — process the transfer quickly",
      "An impersonation 'safe account' scam — stop, explain that banks never ask customers to move money to safe accounts, and follow scam intervention procedures",
      "Card-not-present fraud — cancel the customer's card",
      "Insider fraud — report the customer to HR",
    ], c: [1],
    e: "Safe-account requests are a hallmark of impersonation scams. Break the spell with clear, calm intervention and follow your firm's scam procedures.",
    p: "Use open questions, avoid blaming the customer, and document the intervention.",
    tags: ["APP scams", "impersonation"],
  },
  {
    t: "MULTIPLE", d: "I", course: "account-takeover-identity-fraud",
    s: "Which sequence of events is a strong indicator of account takeover? (Select all that apply.)",
    o: ["Change of phone number or email", "Login from a new device shortly after the change", "New payee added and high-value transfer", "Customer paying their regular utility bill", "Multiple failed login attempts before success"],
    c: [0, 1, 2, 4],
    e: "Contact-detail changes followed by new-device logins, new payees and large transfers — often after failed logins — are classic ATO patterns.",
    tags: ["account takeover"],
  },
  {
    t: "TRUE_FALSE", d: "B", tier: "F", course: "social-engineering-phishing",
    s: "Creating a false sense of urgency is a common social engineering tactic.",
    o: ["True", "False"], c: [0],
    e: "True. Urgency pressures victims to act before thinking or verifying.",
    tags: ["social engineering"],
  },
  {
    t: "MATCHING", d: "B", tier: "F", course: "social-engineering-phishing",
    s: "Match each social engineering channel to its description.",
    m: [["Phishing", "Deceptive emails"], ["Vishing", "Voice calls"], ["Smishing", "SMS text messages"]],
    e: "Phishing uses email, vishing uses voice calls and smishing uses SMS.",
    tags: ["phishing"],
  },
  {
    t: "SINGLE", d: "A", course: "synthetic-identity-application-fraud",
    s: "What is a 'bust-out' in the context of synthetic identity fraud?",
    o: [
      "Closing a mule network",
      "Maximising credit on a nurtured identity and then abandoning the debt",
      "A failed login lockout",
      "A police raid",
    ], c: [1],
    e: "Fraudsters build credit history on a synthetic identity, then draw down all available credit and disappear.",
    tags: ["synthetic identity"],
  },
  {
    t: "SINGLE", d: "I", course: "insider-fraud-employee-misconduct",
    s: "Which control most directly reduces the opportunity for a single employee to both create and pay a fictitious supplier?",
    o: ["Annual training", "Segregation of duties between supplier set-up and payment approval", "Employee of the month awards", "Clean-desk policy"], c: [1],
    e: "Segregation of duties ensures no single person controls the whole process, directly reducing opportunity.",
    tags: ["insider fraud", "controls"],
  },
  {
    t: "SINGLE", d: "I", course: "mule-accounts-fraud-networks",
    s: "Which description best fits an 'unwitting' money mule?",
    o: [
      "A person who sells their account knowingly",
      "A person deceived — for example through a fake job or romance — into moving funds without realising they are criminal proceeds",
      "A bank employee opening accounts for criminals",
      "A person who reports suspicious transfers",
    ], c: [1],
    e: "Unwitting mules are exploited, often via employment or romance scams, and may not realise they are laundering proceeds.",
    tags: ["mules"],
  },
  {
    t: "SHORT_ANSWER", d: "A", course: "fraud-investigations-evidence",
    s: "What is 'chain of custody' and why does it matter?",
    k: ["record|document|log", "integrity|admissib|tamper|reliab"],
    ma: "Chain of custody is the documented record of who collected, handled and transferred evidence, when and how. It preserves the integrity and admissibility of evidence by showing it has not been tampered with.",
    e: "A documented chain of custody demonstrates evidence integrity, which supports disciplinary, civil or criminal outcomes.",
    tags: ["evidence"],
  },
  {
    t: "SINGLE", d: "A", course: "fraud-risk-assessment-prevention",
    s: "The UK 'failure to prevent fraud' offence under the Economic Crime and Corporate Transparency Act 2023 provides a defence if the organisation had:",
    o: ["A fraud hotline", "Reasonable fraud prevention procedures", "Insurance against fraud losses", "No UK employees"], c: [1],
    e: "The defence is having reasonable fraud prevention procedures in place (or that it was reasonable not to have any). The offence applies to large organisations.",
    url: "https://www.gov.uk/government/publications/offence-of-failure-to-prevent-fraud-introduced-by-eccta",
    tags: ["corporate liability", "UK"],
  },
  {
    t: "INVESTIGATION", d: "I", course: "fraud-aml-convergence",
    sc: "Your fraud team confirms an APP scam: a victim sent funds to Account R at your bank. Account R forwarded 90% of the funds within 40 minutes to three other accounts.",
    s: "Which next steps are appropriate? (Select all that apply.)",
    o: [
      "Attempt to freeze or recover remaining funds per policy and law",
      "Trace onward transfers and notify receiving institutions through available channels",
      "Assess Account R and linked accounts for mule behaviour and AML reporting",
      "Ignore the AML dimension because it is a fraud case",
    ], c: [0, 1, 2],
    e: "Fraud cases generate laundering activity. Recovery, tracing, mule assessment and AML reporting should be co-ordinated — the essence of FRAML.",
    tags: ["FRAML", "mules"],
  },
  {
    t: "SINGLE", d: "I", course: "card-digital-payment-fraud",
    s: "Which control replaces a card number with a surrogate value to reduce the impact of data compromise?",
    o: ["Chargeback", "Tokenisation", "Velocity rule", "Address verification"], c: [1],
    e: "Tokenisation substitutes a token for the primary account number, limiting the value of stolen data.",
    tags: ["card fraud"],
  },
];

export const ABC_QUESTIONS: Q[] = [
  {
    t: "SINGLE", d: "B", tier: "F", course: "abc-fundamentals",
    s: "Under the UK Bribery Act 2010, what is the defence to the section 7 offence of failing to prevent bribery?",
    o: ["Lack of knowledge", "Adequate procedures", "The bribe was small", "The bribe was paid overseas"], c: [1],
    e: "Section 7 is a strict liability offence with a defence of having adequate procedures designed to prevent associated persons from bribing.",
    url: "https://www.legislation.gov.uk/ukpga/2010/23/contents",
    tags: ["UK Bribery Act"],
  },
  {
    t: "TRUE_FALSE", d: "B", tier: "F", course: "abc-fundamentals",
    s: "The UK Bribery Act contains an exception for facilitation payments.",
    o: ["True", "False"], c: [1],
    e: "False. The UK Bribery Act has no facilitation payment exception. The US FCPA contains a narrow exception for routine governmental action.",
    tags: ["facilitation payments"],
  },
  {
    t: "MULTIPLE", d: "B", tier: "F", course: "abc-fundamentals",
    s: "Which can constitute 'anything of value' for bribery purposes? (Select all that apply.)",
    o: ["Cash", "Lavish hospitality", "An internship for an official's relative", "A charitable donation requested by a decision-maker", "Nothing that is non-monetary"],
    c: [0, 1, 2, 3],
    e: "Bribes need not be cash: gifts, hospitality, jobs for relatives and donations can all be used to improperly influence decisions.",
    tags: ["bribery"],
  },
  {
    t: "SINGLE", d: "I", course: "abc-fundamentals",
    s: "The FCPA's accounting provisions apply to which companies?",
    o: ["All companies worldwide", "Issuers (companies with securities registered in the US or required to file reports with the SEC)", "Only US government agencies", "Only private companies"], c: [1],
    e: "The FCPA's books-and-records and internal controls provisions apply to issuers.",
    url: "https://www.justice.gov/criminal/criminal-fraud/foreign-corrupt-practices-act",
    tags: ["FCPA"],
  },
  {
    t: "SCENARIO", d: "I", course: "third-party-intermediary-due-diligence",
    sc: "A sales agent in a high-risk market, recommended by a procurement official, requests a 15% success fee paid in advance to an offshore account in a different country.",
    s: "Which is the best course of action?",
    o: [
      "Pay the fee — agents are standard in this market",
      "Do not proceed until enhanced due diligence resolves the red flags (official recommendation, high fee, offshore account); require payment to an account in the agent's name and country and anti-bribery clauses",
      "Pay half the fee as a compromise",
      "Split the fee across several invoices",
    ], c: [1],
    e: "Official recommendation, high commission, advance payment and offshore account are major red flags requiring EDD and strong contractual controls before any engagement.",
    tags: ["third parties"],
  },
  {
    t: "MULTIPLE", d: "I", course: "gifts-hospitality-conflicts",
    s: "Which factors increase the risk of a gift or hospitality being viewed as a bribe? (Select all that apply.)",
    o: ["A pending tender decision", "Recipient is a public official", "Modest value and transparency", "Frequent repeated hospitality to the same person", "Cash or cash equivalents"],
    c: [0, 1, 3, 4],
    e: "Timing around decisions, public officials, frequency and cash equivalents all increase risk; modest, transparent gifts are lower risk.",
    tags: ["gifts and hospitality"],
  },
  {
    t: "SINGLE", d: "I", course: "pep-risk-corruption-exposure",
    s: "Which of the following is a politically exposed person under FATF definitions?",
    o: ["A junior clerk in a ministry", "A senior executive of a state-owned corporation", "A private company's sales manager", "A retired schoolteacher"], c: [1],
    e: "Senior executives of state-owned corporations are included in the FATF PEP definition; junior officials are generally not.",
    tags: ["PEP"],
  },
  {
    t: "MATCHING", d: "A", course: "abc-controls-program-design",
    s: "Match each MoJ principle to an example control.",
    m: [
      ["Top-level commitment", "Board-approved anti-bribery policy statement"],
      ["Risk assessment", "Periodic assessment of country and sector risk"],
      ["Due diligence", "Screening and vetting of intermediaries"],
      ["Monitoring and review", "Testing of the programme and updating procedures"],
    ],
    e: "The MoJ six principles include proportionate procedures, top-level commitment, risk assessment, due diligence, communication and monitoring and review.",
    tags: ["adequate procedures"],
  },
  {
    t: "SINGLE", d: "I", course: "whistleblowing-investigation-management",
    s: "A very low number of whistleblowing reports in a large organisation most likely indicates:",
    o: ["There is no misconduct", "Potentially low awareness or trust in speak-up channels, which should be explored", "The programme is fully effective", "Employees are well paid"], c: [1],
    e: "Low volumes can indicate low awareness or trust. Metrics should be interpreted with context and supported by culture surveys.",
    tags: ["whistleblowing"],
  },
  {
    t: "FILL_BLANK", d: "I", course: "facilitation-payments-improper-benefits",
    s: "A payment made under an imminent threat to health, safety or liberty is usually called a ______ payment.",
    a: ["duress"],
    e: "Duress payments are treated differently from facilitation payments: safety comes first, followed by reporting and accurate recording.",
    tags: ["duress"],
  },
];

export const KYC_TM_INV_QUESTIONS: Q[] = [
  {
    t: "SINGLE", d: "B", tier: "F", course: "customer-due-diligence-kyc",
    s: "Which is a trigger for an event-driven (trigger-based) CDD review?",
    o: ["A customer's birthday", "A material change in ownership of a corporate customer", "A customer logging in to online banking", "A change in the firm's logo"], c: [1],
    e: "Material changes (ownership, activity, adverse media, alerts) should trigger CDD review outside the periodic cycle.",
    tags: ["ongoing due diligence"],
  },
  {
    t: "MULTIPLE", d: "I", course: "customer-due-diligence-kyc",
    s: "For a trust customer, which parties should typically be identified? (Select all that apply.)",
    o: ["Settlor", "Trustees", "Beneficiaries or class of beneficiaries", "Protector (if any)", "The trust's auditor only"],
    c: [0, 1, 2, 3],
    e: "FATF standards call for identification of the settlor, trustee(s), protector (if any), beneficiaries or class of beneficiaries, and any other person exercising effective control.",
    tags: ["trusts"],
  },
  {
    t: "SINGLE", d: "I", course: "transaction-monitoring-investigations",
    s: "Which is the strongest alert closure rationale?",
    o: [
      "Activity appears normal.",
      "Customer is a long-standing client.",
      "December inflows of 120,000 match invoiced seasonal sales from the customer's three largest known buyers; similar spikes occurred in each of the last three Decembers.",
      "No further action needed.",
    ], c: [2],
    e: "Specific, evidence-based rationales that reference amounts, counterparties and history are reproducible and defensible.",
    tags: ["dispositions"],
  },
  {
    t: "TRUE_FALSE", d: "I", course: "transaction-monitoring-investigations",
    s: "Poor data quality, such as unmapped transaction codes, can cause monitoring scenarios to miss suspicious activity.",
    o: ["True", "False"], c: [0],
    e: "True. Data lineage and quality issues are a frequent root cause of monitoring failures and should be tested regularly.",
    tags: ["data quality"],
  },
  {
    t: "SINGLE", d: "B", tier: "F", course: "transaction-monitoring-investigations",
    s: "A rule that alerts when total cash deposits exceed a set amount within 10 days is an example of:",
    o: ["Machine-learning model", "Rules-based scenario", "Network analytics", "Customer risk rating"], c: [1],
    e: "Deterministic threshold logic is a rules-based scenario — transparent and explainable but prone to false positives.",
    tags: ["scenarios"],
  },
  {
    t: "SCENARIO", d: "A", course: "suspicious-activity-reporting",
    sc: "During an investigation, the relationship manager wants to call the customer and explain that 'compliance has flagged some transfers as suspicious and may report them'.",
    s: "What should you advise?",
    o: [
      "Go ahead — transparency is good practice",
      "Do not disclose suspicion or possible reporting; any request for information must be neutral and not reveal the investigation",
      "Email instead of calling",
      "Only mention it if the customer asks",
    ], c: [1],
    e: "Disclosing suspicion or a potential report risks tipping off. Information requests must be neutral.",
    tags: ["tipping off"],
  },
  {
    t: "SHORT_ANSWER", d: "I", course: "suspicious-activity-reporting",
    s: "List the six questions a good SAR narrative should answer.",
    k: ["who", "what", "when", "where", "why", "how"],
    ma: "Who, what, when, where, why and how.",
    e: "The 5W+H structure ensures the narrative covers subjects, activity, timing, location, reasons for suspicion and method.",
    tags: ["SAR writing"],
  },
];

export const TRADE_EXPORT_CRYPTO_GOV_QUESTIONS: Q[] = [
  {
    t: "SINGLE", d: "I", course: "trade-based-money-laundering",
    s: "An importer pays significantly more than market value for goods. This TBML technique is:",
    o: ["Under-invoicing", "Over-invoicing", "Phantom shipment", "Multiple invoicing"], c: [1],
    e: "Over-invoicing moves excess value from importer to exporter.",
    tags: ["TBML"],
  },
  {
    t: "MULTIPLE", d: "I", tier: "F", course: "trade-based-money-laundering",
    s: "Which are TBML red flags? (Select all that apply.)",
    o: ["Unit prices far from market values", "Goods inconsistent with the customer's business", "Consistent, well-documented trade with long-standing buyers", "Unexplained transshipment", "Third-party payments unconnected to the trade"],
    c: [0, 1, 3, 4],
    e: "Pricing anomalies, business inconsistency, unexplained routing and third-party payments are typical TBML indicators.",
    tags: ["TBML"],
  },
  {
    t: "SINGLE", d: "I", course: "trade-finance-financial-crime",
    s: "Why does open-account trade present a challenge for banks detecting TBML?",
    o: [
      "Open account is illegal",
      "Banks typically see only the payment, not the underlying trade documents",
      "Open account is only used for services",
      "It always involves letters of credit",
    ], c: [1],
    e: "In open-account trade, banks usually process payments without reviewing invoices and shipping documents, limiting visibility.",
    tags: ["trade finance"],
  },
  {
    t: "SINGLE", d: "B", tier: "F", course: "export-controls-dual-use-goods",
    s: "What is a 'dual-use' item?",
    o: ["An item sold in two countries", "An item with both civil and military applications", "An item with two owners", "An item exported twice"], c: [1],
    e: "Dual-use items (goods, software, technology) can be used for both civilian and military purposes, including WMD.",
    tags: ["dual-use"],
  },
  {
    t: "SINGLE", d: "I", course: "export-controls-dual-use-goods",
    s: "Under the US EAR, items subject to the EAR but not listed on the Commerce Control List are generally classified as:",
    o: ["ECCN 0A999", "EAR99", "ITAR", "Category XXI"], c: [1],
    e: "EAR99 covers items subject to the EAR that are not specifically listed on the CCL. They may still require a licence for certain destinations, end users or end uses.",
    url: "https://www.bis.gov/",
    tags: ["EAR", "classification"],
  },
  {
    t: "TRUE_FALSE", d: "I", course: "export-controls-dual-use-goods",
    s: "Catch-all controls can require a licence for items that are not on a control list.",
    o: ["True", "False"], c: [0],
    e: "True. Catch-all controls apply when the exporter knows or is informed that items may be intended for WMD or certain military end uses.",
    tags: ["catch-all"],
  },
  {
    t: "SINGLE", d: "I", course: "cryptocurrency-virtual-asset-aml",
    s: "The FATF travel rule for virtual assets is based on which Recommendation?",
    o: ["Recommendation 10", "Recommendation 15", "Recommendation 16", "Recommendation 24"], c: [2],
    e: "The travel rule derives from Recommendation 16 on wire transfers, applied to VASPs through Recommendation 15 and its interpretive note.",
    tags: ["travel rule"],
  },
  {
    t: "SINGLE", d: "I", tier: "F", course: "cryptocurrency-virtual-asset-aml",
    s: "A 'peel chain' in blockchain analysis refers to:",
    o: [
      "A single large transfer to an exchange",
      "A sequence of transactions each peeling off a small amount from a large balance to new addresses",
      "A hardware wallet",
      "A type of stablecoin",
    ], c: [1],
    e: "Peel chains move a large balance through many addresses, peeling off small amounts at each hop — a common laundering pattern.",
    tags: ["crypto typologies"],
  },
  {
    t: "MULTIPLE", d: "A", course: "crypto-assets-vasps",
    s: "When onboarding a VASP as a banking customer, which checks are appropriate? (Select all that apply.)",
    o: ["Licensing/registration status", "Travel-rule compliance approach", "Blockchain analytics capability", "Sanctions controls including IP geolocation", "Price of the VASP's native token"],
    c: [0, 1, 2, 3],
    e: "Licensing, travel-rule compliance, analytics and sanctions controls are core to VASP due diligence; token price is not a compliance control.",
    tags: ["VASP"],
  },
  {
    t: "SINGLE", d: "A", course: "financial-crime-audit-control-testing",
    s: "Testing whether a control, if operated as intended, would mitigate the risk is testing its:",
    o: ["Operating effectiveness", "Design effectiveness", "Cost effectiveness", "Residual risk"], c: [1],
    e: "Design effectiveness assesses whether the control is capable of mitigating the risk; operating effectiveness assesses whether it works consistently in practice.",
    tags: ["control testing"],
  },
  {
    t: "SINGLE", d: "A", course: "enterprise-financial-crime-risk-assessment",
    s: "Which is the correct order of core steps in an enterprise-wide risk assessment?",
    o: [
      "Residual risk → inherent risk → controls",
      "Inherent risk → control effectiveness → residual risk → actions",
      "Actions → controls → inherent risk",
      "Controls → actions → scope",
    ], c: [1],
    e: "Assess inherent risk, evaluate controls, derive residual risk, then define actions against appetite.",
    tags: ["EWRA"],
  },
  {
    t: "SINGLE", d: "A", course: "financial-crime-risk-governance",
    s: "Which is the best example of a measurable financial crime risk appetite metric?",
    o: ["'We care about compliance'", "'No more than 2% of high-risk customer reviews overdue by more than 30 days'", "'Compliance is everyone's job'", "'We follow the law'"], c: [1],
    e: "Appetite metrics should be measurable with thresholds that trigger escalation.",
    tags: ["risk appetite"],
  },
  {
    t: "SINGLE", d: "A", course: "regulatory-investigations-enforcement",
    s: "Which is most commonly cited as a failing in regulatory financial crime enforcement actions?",
    o: ["Too many compliance staff", "Backlogs and weak CDD or monitoring controls", "Excessive board reporting", "Using risk-based approaches"], c: [1],
    e: "Enforcement actions frequently cite CDD deficiencies, monitoring gaps and backlogs, alongside weak governance.",
    tags: ["enforcement"],
  },
];
