type Card = [front: string, back: string, explanation?: string];

export interface SeedDeck {
  slug: string;
  title: string;
  description: string;
  topic: string;
  tier: "FREE" | "PREMIUM";
  cards: Card[];
}

export const DECKS: SeedDeck[] = [
  {
    slug: "aml-terminology", title: "AML Terminology", topic: "aml-ctf", tier: "FREE",
    description: "Core anti-money laundering terms every practitioner should know.",
    cards: [
      ["Placement", "The first stage of money laundering: introducing criminal proceeds into the financial system.", "Often involves cash deposits, structuring or purchase of monetary instruments."],
      ["Layering", "Creating distance between funds and their criminal source through complex transactions.", "Wire chains, shell companies and asset conversion are typical."],
      ["Integration", "Returning laundered funds to the criminal in apparently legitimate form.", "Property, investments and business income are common vehicles."],
      ["Predicate offence", "The underlying crime that generates proceeds that are laundered.", "Examples: fraud, corruption, drug trafficking, tax crimes."],
      ["Structuring", "Splitting transactions to avoid reporting thresholds.", "Also called smurfing when multiple people are used; often an offence in itself."],
      ["Tipping off", "Disclosing that a suspicious activity report has been made or an investigation is under way.", "A criminal offence in many jurisdictions."],
      ["MLRO", "Money Laundering Reporting Officer — the nominated officer who receives internal reports and decides on external filing.", "Equivalent roles include the BSA Officer in the US."],
      ["Risk-based approach", "Identifying and assessing risk and applying proportionate controls.", "Not a zero-risk approach."],
      ["FIU", "Financial Intelligence Unit — the national agency that receives and analyses suspicious transaction reports.", "Examples: FinCEN, UKFIU, FIU-IND."],
      ["Pass-through account", "An account used to move funds rapidly in and out with little retained balance.", "Common in mule and layering activity."],
      ["DNFBPs", "Designated non-financial businesses and professions subject to AML obligations.", "Includes casinos, real estate agents, lawyers, accountants and TCSPs."],
      ["Professional money laundering", "Laundering services provided to criminals by specialists for a fee.", "Highlighted in FATF reporting as a significant threat."],
    ],
  },
  {
    slug: "sanctions-terminology", title: "Sanctions Terminology", topic: "sanctions", tier: "FREE",
    description: "Key sanctions concepts across major regimes.",
    cards: [
      ["Asset freeze", "Prohibition on dealing with a designated person's funds and economic resources, and on making funds available to them.", "Called 'blocking' under US law."],
      ["Designated person", "An individual or entity named under a sanctions regime.", "Also 'listed person' or 'SDN' (US)."],
      ["Nexus", "The connection that brings a person or transaction within a regime's jurisdiction.", "E.g., nationality, territory, currency, goods origin."],
      ["General licence", "An authorisation permitting a class of otherwise prohibited activity for all who meet its conditions.", "Check expiry dates and reporting conditions."],
      ["Specific licence", "An authorisation granted to a named applicant for a particular activity.", "Must be applied for in advance."],
      ["Sectoral sanctions", "Restrictions on specific activities with specific entities in targeted sectors.", "Do not automatically require blocking."],
      ["Making funds available", "Providing funds or economic resources, directly or indirectly, to or for the benefit of a designated person.", "Prohibited under EU and UK asset freezes."],
      ["Secondary sanctions", "Measures targeting non-US persons for specified dealings, even without a US nexus.", "A key consideration for global firms."],
      ["Evasion", "Actions designed to circumvent sanctions, such as using front companies or false documents.", "Often an offence in its own right."],
      ["Strict liability (civil)", "Liability that does not require intent or knowledge.", "OFAC civil penalties are strict liability."],
    ],
  },
  {
    slug: "ofac-international-sanctions", title: "OFAC and International Sanctions", topic: "sanctions", tier: "PREMIUM",
    description: "OFAC lists, processes and international regime comparisons.",
    cards: [
      ["SDN List", "OFAC's Specially Designated Nationals and Blocked Persons List.", "Property of SDNs subject to US jurisdiction is blocked."],
      ["SSI List", "Sectoral Sanctions Identifications List — parties subject to directive-based restrictions.", "Not automatically blocked."],
      ["Blocking vs rejecting", "Block when there is a blocked interest; reject prohibited transactions without a blockable interest.", "Both require reporting to OFAC within 10 business days."],
      ["US person (OFAC)", "US citizens and permanent residents anywhere, US entities and their foreign branches, and anyone in the US.", ""],
      ["OFAC compliance framework components", "Management commitment, risk assessment, internal controls, testing and auditing, training.", "From OFAC's 2019 Framework."],
      ["OFSI", "Office of Financial Sanctions Implementation — HM Treasury body implementing UK financial sanctions.", ""],
      ["SAMLA 2018", "The UK Sanctions and Anti-Money Laundering Act, the legal basis for UK sanctions regulations.", ""],
      ["Article 215 TFEU", "Treaty basis for EU Council Regulations implementing economic restrictive measures.", ""],
      ["EU Blocking Statute", "Regulation protecting EU operators against specified extraterritorial third-country sanctions.", "Council Regulation (EC) No 2271/96."],
      ["UN Chapter VII", "Part of the UN Charter under which the Security Council adopts binding sanctions.", ""],
    ],
  },
  {
    slug: "ownership-and-control", title: "Ownership and Control", topic: "sanctions", tier: "PREMIUM",
    description: "Thresholds, aggregation and control indicators.",
    cards: [
      ["OFAC 50 Percent Rule", "Entities owned 50% or more in aggregate, directly or indirectly, by blocked persons are blocked.", "Revised guidance issued August 2014."],
      ["EU/UK ownership test", "More than 50% ownership by a designated person, plus control tests.", "Note the difference from OFAC's '50% or more'."],
      ["Aggregation", "Adding together holdings of multiple blocked persons.", "Applies under OFAC's rule."],
      ["Indirect ownership", "Ownership held through intermediate entities.", "Under OFAC, counted through entities that are themselves blocked."],
      ["Control indicators", "Board appointment rights, voting agreements, directing use of assets, shared management.", "Relevant to EU and UK assessments."],
      ["Nominee shareholder", "A person holding shares on behalf of another.", "Can conceal the true owner."],
      ["Post-designation transfer", "Share transfers shortly after designation, often to relatives or associates.", "A classic evasion red flag."],
      ["Beneficial owner (AML)", "The natural person who ultimately owns or controls a customer.", "Often a 25% threshold plus control."],
    ],
  },
  {
    slug: "fraud-typologies", title: "Fraud Typologies", topic: "fraud", tier: "FREE",
    description: "Recognise the major fraud types.",
    cards: [
      ["APP fraud", "Authorised push payment fraud — the victim is manipulated into sending money.", "Includes impersonation, investment and romance scams."],
      ["Account takeover", "A criminal gains control of a genuine customer's account.", "Often via phishing, credential stuffing or SIM swap."],
      ["Synthetic identity", "A fabricated identity combining real and fake data.", "Nurtured then 'busted out'."],
      ["First-party fraud", "Fraud committed by the customer against the firm.", "E.g., false income on applications."],
      ["Money mule", "A person whose account is used to move criminal proceeds.", "Complicit, recruited or unwitting."],
      ["Business email compromise", "Spoofed or compromised email used to redirect payments.", "Verify payee changes by independent call-back."],
      ["Fraud triangle", "Pressure, opportunity, rationalisation.", "Developed by Donald Cressey."],
      ["Friendly fraud", "A genuine cardholder falsely disputes a legitimate transaction.", ""],
      ["Credential stuffing", "Automated use of leaked username/password pairs across sites.", ""],
      ["Bust-out", "Maximising credit then abandoning the debt.", "Common endpoint of synthetic identity fraud."],
    ],
  },
  {
    slug: "abc-terminology", title: "ABC Terminology", topic: "abc", tier: "FREE",
    description: "Anti-bribery and corruption concepts.",
    cards: [
      ["Bribery", "Offering, giving, requesting or accepting anything of value to improperly influence someone.", ""],
      ["Facilitation payment", "A small unofficial payment to speed up routine government action.", "Prohibited under the UK Bribery Act; narrow FCPA exception."],
      ["Adequate procedures", "The defence to the UK Bribery Act section 7 offence.", "Six principles in MoJ guidance."],
      ["Associated person", "A person who performs services for or on behalf of an organisation.", "Relevant to section 7 UK Bribery Act."],
      ["FCPA accounting provisions", "Books-and-records and internal controls requirements for issuers.", ""],
      ["PEP", "Politically exposed person — someone entrusted with a prominent public function.", "Includes family and close associates."],
      ["Duress payment", "A payment made under imminent threat to health, safety or liberty.", "Safety first; report afterwards."],
      ["Conflict of interest", "A situation where personal interests may influence professional judgement.", "Declare and manage."],
      ["Kickback", "A portion of contract value returned to a decision-maker.", ""],
      ["DPA", "Deferred prosecution agreement — prosecution suspended subject to conditions.", ""],
    ],
  },
  {
    slug: "kyc-due-diligence", title: "KYC and Due Diligence", topic: "kyc-cdd", tier: "FREE",
    description: "Identification, verification and enhanced due diligence.",
    cards: [
      ["Identification vs verification", "Identification collects information; verification confirms it with reliable, independent sources.", ""],
      ["Source of funds", "Origin of the specific funds used in a transaction or relationship.", ""],
      ["Source of wealth", "How the customer accumulated their total net worth.", ""],
      ["EDD", "Enhanced due diligence — additional measures for higher-risk relationships.", "Senior approval, corroboration, more frequent review."],
      ["Senior managing official", "Recorded when no natural person meets beneficial ownership criteria.", ""],
      ["Trigger event review", "CDD review prompted by material change, alert or adverse media.", ""],
      ["Simplified due diligence", "Reduced measures permitted for demonstrably lower-risk situations where the law allows.", ""],
      ["Adverse media", "Negative news linking a customer to financial crime or misconduct.", "Assess credibility, relevance and materiality."],
    ],
  },
  {
    slug: "transaction-monitoring-essentials", title: "Transaction Monitoring", topic: "transaction-monitoring", tier: "PREMIUM",
    description: "Scenarios, tuning and alert handling.",
    cards: [
      ["Scenario", "Detection logic mapped to a typology or risk.", ""],
      ["Above-the-line testing", "Reviewing alerts generated at current thresholds for productivity.", ""],
      ["Below-the-line testing", "Sampling activity just below thresholds to test for missed suspicious behaviour.", ""],
      ["Alert disposition", "The documented decision and rationale for an alert.", "Should be specific and reproducible."],
      ["Coverage assessment", "Mapping risks to detection capabilities to identify gaps.", ""],
      ["Conversion rate", "Proportion of alerts escalated to cases or reports.", "A productivity metric; interpret with care."],
      ["Peer-group analysis", "Comparing a customer's behaviour with similar customers.", ""],
      ["Data lineage", "Tracing data from source systems to monitoring.", "Gaps cause missed detection."],
    ],
  },
  {
    slug: "financial-crime-regulations", title: "Financial Crime Regulations", topic: "governance", tier: "PREMIUM",
    description: "Key laws and standards at a glance.",
    cards: [
      ["FATF Recommendations", "International AML/CFT/CPF standards, comprehensively revised in 2012.", ""],
      ["Bank Secrecy Act", "The core US AML statute, administered by FinCEN.", ""],
      ["POCA 2002", "UK Proceeds of Crime Act — principal money laundering offences.", ""],
      ["MLRs 2017", "UK Money Laundering Regulations setting preventive requirements.", ""],
      ["PMLA 2002", "India's Prevention of Money Laundering Act.", "Reporting to FIU-IND."],
      ["UK Bribery Act 2010", "UK anti-bribery law including the section 7 corporate offence.", ""],
      ["FCPA", "US Foreign Corrupt Practices Act (1977).", ""],
      ["ECCTA 2023", "UK Economic Crime and Corporate Transparency Act, including failure to prevent fraud.", "Offence in force from 1 September 2025."],
      ["EU AMLR", "Regulation (EU) 2024/1624 — the directly applicable EU AML rulebook.", "Applies generally from 10 July 2027."],
      ["AMLA", "The EU Anti-Money Laundering Authority established by Regulation (EU) 2024/1620.", ""],
    ],
  },
  {
    slug: "export-controls-essentials", title: "Export Controls", topic: "export-controls", tier: "PREMIUM",
    description: "Dual-use, classification and diversion.",
    cards: [
      ["Dual-use item", "Goods, software or technology with civil and military applications.", ""],
      ["ECCN", "Export Control Classification Number on the US Commerce Control List.", ""],
      ["EAR99", "Items subject to the EAR but not on the Commerce Control List.", ""],
      ["Catch-all control", "Licence requirement for unlisted items when WMD or military end use is known or suspected.", ""],
      ["Entity List", "BIS list of parties subject to additional US export licence requirements.", ""],
      ["Wassenaar Arrangement", "Multilateral regime for conventional arms and dual-use goods.", ""],
      ["End-user statement", "Document declaring the end user and intended use of exported items.", ""],
      ["Regulation (EU) 2021/821", "The EU Dual-Use Regulation.", ""],
    ],
  },
  {
    slug: "trade-finance-essentials", title: "Trade Finance", topic: "trade-based", tier: "PREMIUM",
    description: "Trade products and TBML indicators.",
    cards: [
      ["Letter of credit", "A bank undertaking to pay against complying documents.", ""],
      ["Documentary collection", "Banks exchange documents for payment or acceptance without a payment undertaking.", ""],
      ["Open account", "Goods shipped before payment without bank documentary involvement.", "Majority of global trade."],
      ["Bill of lading", "Transport document evidencing shipment and, often, title to goods.", ""],
      ["Over-invoicing", "Invoicing above true value to move value to the exporter.", ""],
      ["Under-invoicing", "Invoicing below true value to move value to the importer.", ""],
      ["Phantom shipment", "Payment for goods that are never shipped.", ""],
      ["Transshipment", "Moving goods through an intermediate port or country.", "Can disguise origin or destination."],
    ],
  },
  {
    slug: "crypto-virtual-assets", title: "Crypto and Virtual Assets", topic: "crypto", tier: "FREE",
    description: "VASPs, wallets and crypto typologies.",
    cards: [
      ["VASP", "Virtual asset service provider — exchanges, transfers, safekeeps or administers virtual assets for others.", ""],
      ["Travel rule", "Requirement to obtain and transmit originator and beneficiary information with transfers.", "FATF R.16 applied to VASPs."],
      ["Self-hosted wallet", "A wallet controlled directly by its user.", ""],
      ["Mixer", "A service that pools and redistributes funds to obscure transaction trails.", ""],
      ["Chain hopping", "Rapidly moving value across different assets or blockchains.", ""],
      ["Peel chain", "Sequence of transfers peeling small amounts off a large balance.", ""],
      ["Stablecoin", "A crypto-asset designed to maintain a stable value against a reference asset.", ""],
      ["MiCA", "EU Markets in Crypto-Assets Regulation (EU) 2023/1114.", ""],
    ],
  },
];
