export const HELP_CATEGORIES = [
  "Getting Started",
  "Login and Account",
  "Course Enrollment",
  "Question Bank",
  "Flashcards",
  "Certificates and Assessments",
  "Payments and Membership",
  "Technical Troubleshooting",
] as const;

export const HELP_ARTICLES = [
  { slug: "getting-started", title: "Getting started with FinCrime Academy", category: "Getting Started", related: ["choosing-a-learning-path", "how-enrollment-works"], content: `Welcome! Here's how to get the most out of the platform.\n\n1. **Create your account** and choose your interests and level during registration.\n2. **Visit your dashboard** for recommendations based on your interests and results.\n3. **Enrol in a course** from the Academy and track progress lesson by lesson.\n4. **Practise** with the Question Bank and review explanations.\n5. **Revise** with flashcards — the spaced-repetition scheduler tells you what's due each day.` },
  { slug: "choosing-a-learning-path", title: "Choosing a learning path", category: "Getting Started", related: ["getting-started"], content: `Start with a **Beginner** course in your main area (e.g., AML/CFT Fundamentals or Global Sanctions Fundamentals), then use the **Exam Readiness Assessment** to identify weaker topics. Your dashboard will recommend courses and practice sessions based on your results.` },
  { slug: "reset-password", title: "Resetting your password", category: "Login and Account", related: ["account-security"], content: `Use **Forgot password** on the sign-in page. Enter your email and follow the link sent to you (valid for 1 hour). For security, resetting your password signs you out on all devices.` },
  { slug: "account-security", title: "Keeping your account secure", category: "Login and Account", related: ["reset-password"], content: `Use a unique password of at least 10 characters. Sign out on shared devices. You can review and export your data or delete your account from **Account settings**.` },
  { slug: "how-enrollment-works", title: "How course enrolment works", category: "Course Enrollment", related: ["course-progress"], content: `Open any course and select **Enrol**. Free courses are available to all registered learners. Premium courses require a Premium membership, a relevant learning package, or a corporate assignment. Enrolled courses appear in **My Learning**.` },
  { slug: "course-progress", title: "How course progress is tracked", category: "Course Enrollment", related: ["how-enrollment-works", "earning-certificates"], content: `Progress is saved automatically as you work through lessons. Select **Mark as complete** at the end of each lesson. You can leave and resume at any time from **Continue learning** on your dashboard.` },
  { slug: "practice-modes", title: "Question Bank practice modes", category: "Question Bank", related: ["reviewing-answers"], content: `Choose **Quick (5)**, **Standard (10)** or **Deep (25)** practice, **Topic Mastery** (focuses on your weaker areas), the **Daily Challenge**, or **Incorrect Answer Review**. Timed mode adds a countdown; sessions can be resumed if you leave.` },
  { slug: "reviewing-answers", title: "Reviewing answers and explanations", category: "Question Bank", related: ["practice-modes"], content: `After submitting, you'll see your score, a topic breakdown, and each question's explanation, including why incorrect options are wrong. Bookmark or flag questions to revisit them later.` },
  { slug: "how-spaced-repetition-works", title: "How spaced repetition works", category: "Flashcards", related: [], content: `After viewing a card's answer, rate it: **Needs revision**, **Difficult**, **Medium** or **Easy**. Cards you find hard return sooner; cards you know well are scheduled further apart. Cards reach **Mastered** when their interval reaches 21 days. See the full algorithm in our documentation.` },
  { slug: "earning-certificates", title: "Earning a certificate", category: "Certificates and Assessments", related: ["verify-certificate"], content: `Complete every lesson in a certificate-eligible course and pass the final assessment (the passing score is shown on the course page). Your certificate is issued automatically with a unique verification code.\n\n**Important:** FinCrime Academy certificates are internal completion certificates. They are not external accredited qualifications.` },
  { slug: "verify-certificate", title: "Verifying a certificate", category: "Certificates and Assessments", related: ["earning-certificates"], content: `Anyone can verify a certificate at **/certificates/verify** using the verification code printed on the certificate.` },
  { slug: "membership-billing", title: "Memberships, billing and invoices", category: "Payments and Membership", related: ["fee-assistance"], content: `View your plan, payment history and invoices under **Account settings → Billing**. You can cancel a subscription at any time; access continues until the end of the paid period.` },
  { slug: "fee-assistance", title: "Fee assistance and scholarships", category: "Payments and Membership", related: ["membership-billing"], content: `If cost is a barrier, apply for fee assistance from the Pricing page. Applications are reviewed by our team and, where approved, a discount is applied to your account.` },
  { slug: "browser-support", title: "Supported browsers and troubleshooting", category: "Technical Troubleshooting", related: [], content: `We support the latest versions of Chrome, Edge, Firefox and Safari. If videos don't load, check that your network allows YouTube embeds, or use the **Open on YouTube** link. Clearing cached site data can resolve display issues.` },
];

export const FAQS = [
  { q: "Is FinCrime Academy an accredited certification body?", a: "No. Our certificates confirm completion of our courses and assessments. They are not external accredited qualifications, and our readiness scores do not guarantee success in any external examination." },
  { q: "Can I use the platform for free?", a: "Yes. Free membership includes selected foundational courses, a set of free practice questions, selected flashcard decks, videos and knowledge resources." },
  { q: "Are the case studies real?", a: "Training case studies are fictional and anonymised unless explicitly labelled as based on public enforcement actions." },
  { q: "How are questions reviewed?", a: "Questions are written and reviewed by our editorial team before publication. Each includes explanations and, where relevant, a source reference. You can report an issue via a support ticket." },
  { q: "Can my team use FinCrime Academy?", a: "Yes. Corporate membership offers team management, course assignments, deadlines and completion reports. Contact us via the Corporate Training page." },
];

export const PLANS = [
  { slug: "free", name: "Free", tier: "FREE", priceCents: 0, interval: "MONTH", order: 0, description: "Start learning with foundational content.", features: ["Selected foundational courses", "Free practice questions", "Selected flashcard decks with spaced repetition", "Selected videos and knowledge resources", "Basic learning dashboard"] },
  { slug: "premium-monthly", name: "Premium", tier: "PREMIUM", priceCents: 2900, interval: "MONTH", order: 1, description: "Full access for individual professionals, billed monthly.", features: ["Full eligible course catalog", "Expanded question bank", "Mock examinations & readiness assessment", "Full flashcard library", "Performance analytics", "Advanced case study simulations", "Downloadable resources", "Eligible completion certificates"] },
  { slug: "premium-annual", name: "Premium Annual", tier: "PREMIUM", priceCents: 24900, interval: "YEAR", order: 2, description: "Everything in Premium, billed annually.", features: ["Everything in Premium", "Billed once per year"] },
  { slug: "corporate", name: "Corporate", tier: "CORPORATE", priceCents: 0, interval: "YEAR", order: 3, description: "Team learning with management and reporting. Priced per team — contact us.", features: ["Team-based learning", "Course assignments & deadlines", "Employee progress dashboard", "Completion reports", "Bulk learner management", "Customised programmes", "Corporate support"] },
] as const;

export const PACKAGES = [
  { slug: "aml-mastery", name: "AML Mastery", priceCents: 14900, order: 0, topicSlugs: ["aml-ctf", "kyc-cdd", "transaction-monitoring"], entitlements: ["FULL_QUESTION_BANK", "MOCK_EXAMS", "FULL_FLASHCARDS", "DOWNLOADS", "ANALYTICS"], description: "AML courses, mock exams, question bank access and flashcards.", features: ["All AML, KYC and monitoring courses", "AML question bank", "Mock examinations", "AML flashcard decks"] },
  { slug: "sanctions-professional", name: "Sanctions Professional", priceCents: 14900, order: 1, topicSlugs: ["sanctions", "export-controls"], entitlements: ["FULL_QUESTION_BANK", "MOCK_EXAMS", "FULL_FLASHCARDS", "ADVANCED_CASES", "DOWNLOADS", "ANALYTICS"], description: "Sanctions courses, ownership analysis, screening practice, mock exams and flashcards.", features: ["All sanctions & export control courses", "Ownership analysis practice", "Screening case simulations", "Mock examinations", "Sanctions flashcards"] },
  { slug: "financial-crime-investigator", name: "Financial Crime Investigator", priceCents: 14900, order: 2, topicSlugs: ["investigations", "transaction-monitoring", "fraud"], entitlements: ["FULL_QUESTION_BANK", "MOCK_EXAMS", "ADVANCED_CASES", "ANALYTICS"], description: "AML and fraud investigations, transaction monitoring, case simulations and assessments.", features: ["Investigation & monitoring courses", "Fraud courses", "Case simulations", "Assessment exercises"] },
  { slug: "abc-compliance-professional", name: "ABC Compliance Professional", priceCents: 12900, order: 3, topicSlugs: ["abc"], entitlements: ["FULL_QUESTION_BANK", "FULL_FLASHCARDS", "ADVANCED_CASES", "DOWNLOADS"], description: "ABC courses, third-party due diligence, investigations and practice questions.", features: ["All ABC courses", "Third-party due diligence", "ABC case studies", "ABC practice questions"] },
  { slug: "complete-academy", name: "Complete Financial Crime Academy", priceCents: 29900, order: 4, topicSlugs: [], entitlements: ["FULL_QUESTION_BANK", "MOCK_EXAMS", "FULL_FLASHCARDS", "ANALYTICS", "ADVANCED_CASES", "DOWNLOADS", "PREMIUM_VIDEOS"], description: "The full eligible catalog, question bank, flashcards, mock exams, video library and case studies for 12 months.", features: ["Full eligible course catalog", "Complete question bank", "All flashcards", "All mock exams", "Video library", "All case studies"] },
] as const;

export const ASSESSMENTS = [
  { slug: "quick-assessment", name: "Quick Assessment", type: "MOCK_EXAM", questionCount: 20, timeLimitMinutes: 25, accessTier: "FREE", order: 0, description: "20 questions across all topics in 25 minutes. A fast check of your knowledge." },
  { slug: "standard-mock-exam", name: "Standard Mock Exam", type: "MOCK_EXAM", questionCount: 50, timeLimitMinutes: 60, accessTier: "PREMIUM", order: 1, description: "50 questions, 60 minutes, randomised across topics." },
  { slug: "full-length-mock-100", name: "Full-Length Mock Exam (100)", type: "MOCK_EXAM", questionCount: 100, timeLimitMinutes: 120, accessTier: "PREMIUM", order: 2, description: "100 questions, 120 minutes. Builds stamina and time management." },
  { slug: "full-length-mock-120", name: "Full-Length Mock Exam (120)", type: "MOCK_EXAM", questionCount: 120, timeLimitMinutes: 150, accessTier: "PREMIUM", order: 3, description: "120 questions, 150 minutes." },
  { slug: "advanced-professional-assessment", name: "Advanced Professional Assessment", type: "MOCK_EXAM", questionCount: 40, timeLimitMinutes: 60, accessTier: "PREMIUM", order: 4, configurable: true, difficulty: "ADVANCED", description: "Configurable topics, difficulty, question count and time limit." },
  { slug: "exam-readiness", name: "Exam Readiness Assessment", type: "READINESS", questionCount: 30, timeLimitMinutes: 40, accessTier: "FREE", order: 5, description: "A diagnostic across all topics with strengths, gaps and a personalised revision plan." },
] as const;
